Repository puppetlabs/puppetlabs-accounts, pull requests merged in 2018-09, with the labels that each got.

#174 Only take care of ssh-keys if ensure is set to 'present'
  manifests/user.pp
Labels: bugfix

#183 (MODULES-7827) - Update to pre test logic for puppet 6
  spec/spec_helper_acceptance.rb
Labels: maintenance

#185 pdksync - (MODULES-6805) metadata.json shows support for puppet 6
  metadata.json
Labels: feature
