Repository puppetlabs/puppetlabs-accounts, pull requests merged in 2019-05, with the labels that each got.

#220 (MODULES-8909) Allow periods in usernames.
  spec/acceptance/accounts_spec.rb
  spec/acceptance/user_spec.rb
  spec/type_aliases/user_name_spec.rb
  types/user/name.pp
Labels: bugfix

#223 (MODULES-9017) - update metadata to support current version of stdlib
  metadata.json
Labels: maintenance

#221 (MODULES-7469) Add password_max_age parameter
  README.md
  manifests/user.pp
  spec/acceptance/accounts_spec.rb
  spec/defines/accounts_user_spec.rb
  types/user/passwordmaxage.pp
  types/user/resource.pp
Labels: feature

#227 (FM-8023) Add RedHat 8 support
  metadata.json
  spec/acceptance/locales_spec.rb
  spec/spec_helper_acceptance.rb
Labels: feature

#228 (MODULES-9179) Release prep v4.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
