Repository puppetlabs/puppetlabs-accounts, pull requests merged in 2019-11, with the labels that each got.

#275 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#277 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#278 (FM-8671) - Support added for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#279 (MODULES-10072) Release Merge back v6.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#280 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance
