Repository puppetlabs/puppetlabs-accounts, pull requests merged in 2021-03, with the labels that each got.

#368 Update metadata.json - remove ubuntu 14.04
  metadata.json
Labels: backwards-incompatible

#372 pdksync - PDK Update - Replace Travis and Appveyor with Github Actions
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#373 (IAC-1497) - Removal of unsupported `translate` dependency
  .fixtures.yml
  locales/config.yaml
  locales/ja/puppetlabs-accounts.po
  locales/puppetlabs-accounts.pot
  manifests/home_dir.pp
  manifests/key_management.pp
  manifests/manage_keys.pp
  manifests/user.pp
  metadata.json
Labels: bugfix
