Repository puppetlabs/puppetlabs-accounts, pull requests merged in 2024-05, with the labels that each got.

#484 accounts_ssh_authorized_keys_line_parser: Output regex matches when sshkey format isnt correct
  lib/puppet/functions/accounts_ssh_authorized_keys_line_parser.rb
Labels: feature, community

#483 usermanagement: prohibit empty ssh keys
  REFERENCE.md
  lib/puppet/functions/accounts_ssh_authorized_keys_line_parser.rb
  manifests/key_management.pp
  manifests/manage_keys.pp
  manifests/user.pp
  spec/functions/accounts_ssh_authorized_keys_line_parser_spec.rb
Labels: bugfix, community

#463 docs: Fix "beginning with accounts" terminology in the README
  README.md
Labels: maintenance, community

#486 pdksync - (ITHELP-87329) - replace pull_request_target with pull_request
  .github/workflows/mend.yml
Labels: maintenance
